development:
  adapter: postgresql
  encoding: unicode
  database: picdora_development
  pool: 5
  username: eli
  password: asdfasdf

test:
  adapter: postgresql
  encoding: unicode
  database: picdora_test
  pool: 5
  username: eli
  password: asdfasdf

production:
  adapter: postgresql
  encoding: unicode
  database: rails
  pool: 5
  host: localhost
  username: rails
  password: y3IUAoEvkZ


